# Generated by Django 4.2.6 on 2023-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='record_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
