# Generated by Django 4.2.6 on 2023-10-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_band_hometown'),
        ('listings', '0007_band_record_company'),
    ]

    operations = [
    ]
