# Generated by Django 4.2.6 on 2023-10-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_merge_0007_band_hometown_0007_band_record_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='band',
            name='record_company',
        ),
    ]
